export const tickets = [
    {
      id: "1",
      titulo: "Erro ao acessar sistema",
      cliente: "Empresa Alpha",
      status: "Aberto",
      prioridade: "Alta",
      data: "06/03/2026",
    },
    {
      id: "2",
      titulo: "Impressora não conecta",
      cliente: "Empresa Beta",
      status: "Em andamento",
      prioridade: "Média",
      data: "05/03/2026",
    },
    {
      id: "3",
      titulo: "Reset de senha",
      cliente: "Empresa Gama",
      status: "Resolvido",
      prioridade: "Baixa",
      data: "04/03/2026",
    },
    {
      id: "4",
      titulo: "Sistema travando ao emitir relatório",
      cliente: "Construtora Horizonte",
      status: "Aberto",
      prioridade: "Alta",
      data: "06/03/2026",
    },
    {
      id: "5",
      titulo: "Usuário sem acesso ao módulo financeiro",
      cliente: "Grupo Via Norte",
      status: "Em andamento",
      prioridade: "Alta",
      data: "05/03/2026",
    },
    {
      id: "6",
      titulo: "Erro ao anexar arquivos no chamado",
      cliente: "Metalúrgica União",
      status: "Resolvido",
      prioridade: "Média",
      data: "04/03/2026",
    },
    {
      id: "7",
      titulo: "Lentidão no carregamento da dashboard",
      cliente: "Clínica São Lucas",
      status: "Aberto",
      prioridade: "Média",
      data: "03/03/2026",
    },
    {
      id: "8",
      titulo: "Falha na integração com o e-mail corporativo",
      cliente: "Tech Prime",
      status: "Em andamento",
      prioridade: "Alta",
      data: "03/03/2026",
    },
    {
      id: "9",
      titulo: "Cadastro de cliente não salva alterações",
      cliente: "Distribuidora Central",
      status: "Aberto",
      prioridade: "Média",
      data: "02/03/2026",
    },
    {
      id: "10",
      titulo: "Dúvida sobre redefinição de senha",
      cliente: "Loja Nova Era",
      status: "Resolvido",
      prioridade: "Baixa",
      data: "02/03/2026",
    },
    {
      id: "11",
      titulo: "Erro 500 ao abrir tela de pedidos",
      cliente: "Comercial Batista",
      status: "Aberto",
      prioridade: "Alta",
      data: "01/03/2026",
    },
    {
      id: "12",
      titulo: "Permissão incorreta para usuário operador",
      cliente: "Auto Peças Real",
      status: "Em andamento",
      prioridade: "Média",
      data: "01/03/2026",
    },
  ];