export const tickets = [
  {
    id: "1",
    titulo: "Erro ao acessar sistema",
    cliente: "Empresa Alpha",
    status: "Aberto",
    prioridade: "Alta",
    data: "06/03/2026",
  },
  {
    id: "2",
    titulo: "Impressora não conecta",
    cliente: "Empresa Beta",
    status: "Em andamento",
    prioridade: "Média",
    data: "05/03/2026",
  },
  {
    id: "3",
    titulo: "Reset de senha",
    cliente: "Empresa Gama",
    status: "Resolvido",
    prioridade: "Baixa",
    data: "04/03/2026",
  },
  {
    id: "4",
    titulo: "Sistema travando ao emitir relatório",
    cliente: "Construtora Horizonte",
    status: "Aberto",
    prioridade: "Alta",
    data: "06/03/2026",
  },
  {
    id: "5",
    titulo: "Usuário sem acesso ao módulo financeiro",
    cliente: "Grupo Via Norte",
    status: "Em andamento",
    prioridade: "Alta",
    data: "05/03/2026",
  },
  {
    id: "6",
    titulo: "Erro ao anexar arquivos no chamado",
    cliente: "Metalúrgica União",
    status: "Resolvido",
    prioridade: "Média",
    data: "04/03/2026",
  },
  {
    id: "7",
    titulo: "Lentidão no carregamento da dashboard",
    cliente: "Clínica São Lucas",
    status: "Aberto",
    prioridade: "Média",
    data: "03/03/2026",
  },
  {
    id: "8",
    titulo: "Falha na integração com o e-mail corporativo",
    cliente: "Tech Prime",
    status: "Em andamento",
    prioridade: "Alta",
    data: "03/03/2026",
  },
  {
    id: "9",
    titulo: "Cadastro de cliente não salva alterações",
    cliente: "Distribuidora Central",
    status: "Aberto",
    prioridade: "Média",
    data: "02/03/2026",
  },
  {
    id: "10",
    titulo: "Dúvida sobre redefinição de senha",
    cliente: "Loja Nova Era",
    status: "Resolvido",
    prioridade: "Baixa",
    data: "02/03/2026",
  },
  {
    id: "11",
    titulo: "Erro 500 ao abrir tela de pedidos",
    cliente: "Comercial Batista",
    status: "Aberto",
    prioridade: "Alta",
    data: "01/03/2026",
  },
  {
    id: "12",
    titulo: "Permissão incorreta para usuário operador",
    cliente: "Auto Peças Real",
    status: "Em andamento",
    prioridade: "Média",
    data: "01/03/2026",
  },
  {
    id: "13",
    titulo: "Cliente não consegue gerar segunda via do boleto",
    cliente: "Rede Martins",
    status: "Aberto",
    prioridade: "Média",
    data: "28/02/2026",
  },
  {
    id: "14",
    titulo: "Campo de observação não aparece no formulário",
    cliente: "Farmácia Bela Vista",
    status: "Resolvido",
    prioridade: "Baixa",
    data: "28/02/2026",
  },
  {
    id: "15",
    titulo: "Sistema desconecta sozinho após alguns minutos",
    cliente: "Transportadora Cruzeiro",
    status: "Em andamento",
    prioridade: "Alta",
    data: "27/02/2026",
  },
  {
    id: "16",
    titulo: "Erro ao importar planilha de produtos",
    cliente: "Atacado Fernandes",
    status: "Aberto",
    prioridade: "Alta",
    data: "27/02/2026",
  },
  {
    id: "17",
    titulo: "Tela de login muito lenta no primeiro acesso",
    cliente: "Escola Novo Saber",
    status: "Resolvido",
    prioridade: "Média",
    data: "26/02/2026",
  },
  {
    id: "18",
    titulo: "Relatório de vendas mostrando valores duplicados",
    cliente: "Mercado Bom Preço",
    status: "Em andamento",
    prioridade: "Alta",
    data: "26/02/2026",
  },
  {
    id: "19",
    titulo: "Botão de salvar pedido não responde",
    cliente: "Papelaria Ideal",
    status: "Aberto",
    prioridade: "Alta",
    data: "25/02/2026",
  },
  {
    id: "20",
    titulo: "Usuário pediu troca de e-mail de acesso",
    cliente: "Studio Forma",
    status: "Resolvido",
    prioridade: "Baixa",
    data: "25/02/2026",
  },
  {
    id: "21",
    titulo: "Produtos não aparecem na busca interna",
    cliente: "Casa do Agricultor",
    status: "Em andamento",
    prioridade: "Média",
    data: "24/02/2026",
  },
  {
    id: "22",
    titulo: "Erro ao fechar caixa no fim do expediente",
    cliente: "Padaria Pão Nobre",
    status: "Aberto",
    prioridade: "Alta",
    data: "24/02/2026",
  },
  {
    id: "23",
    titulo: "PDF do relatório sai em branco",
    cliente: "Grupo ServMais",
    status: "Em andamento",
    prioridade: "Média",
    data: "23/02/2026",
  },
  {
    id: "24",
    titulo: "Cadastro de fornecedor sem opção de editar",
    cliente: "Eletro Vale",
    status: "Resolvido",
    prioridade: "Baixa",
    data: "23/02/2026",
  },
  {
    id: "25",
    titulo: "Sistema não envia notificação por e-mail",
    cliente: "Hospital Esperança",
    status: "Aberto",
    prioridade: "Alta",
    data: "22/02/2026",
  },
  {
    id: "26",
    titulo: "Erro ao vincular usuário a filial",
    cliente: "Posto Avenida",
    status: "Em andamento",
    prioridade: "Média",
    data: "22/02/2026",
  },
  {
    id: "27",
    titulo: "Tela de estoque abre sem carregar os dados",
    cliente: "Supermercado União",
    status: "Aberto",
    prioridade: "Média",
    data: "21/02/2026",
  },
  {
    id: "28",
    titulo: "Layout desalinhado na tela de orçamento",
    cliente: "Móveis Castro",
    status: "Resolvido",
    prioridade: "Baixa",
    data: "21/02/2026",
  },
  {
    id: "29",
    titulo: "Usuário não consegue alterar a própria senha",
    cliente: "Clube Imperial",
    status: "Em andamento",
    prioridade: "Média",
    data: "20/02/2026",
  },
  {
    id: "30",
    titulo: "Dashboard não atualiza os números em tempo real",
    cliente: "Logística Brasil Sul",
    status: "Aberto",
    prioridade: "Alta",
    data: "20/02/2026",
  },
];